action changes

diff --git a/.github/workflows/sdk-python.yml b/.github/workflows/sdk-python.yml
--- a/.github/workflows/sdk-python.yml
+++ b/.github/workflows/sdk-python.yml
@@ -51,13 +51,6 @@ jobs:
           echo "Wait for NCTL"
           sleep 30s
 
-#      # Checkout the latest Casper Python SDK from their repo ready for a build
-#      - name: Checkout SDK source code
-#        uses: actions/checkout@v2
-#        with:
-#          repository: casper-network/casper-python-sdk
-#          ref: ${{ github.event.inputs.python-repo }}
-#          path: casper-python-sdk
 
       # Checkout the test platform Python code
       - name: Checkout the test platform Python code
@@ -76,13 +69,10 @@ jobs:
       # Build environment
       - name: Build test environment
         run: |
-          ls -ltra
           cd terminus-python/sh 
           chmod +x docker-copy-assets.sh 
           ./docker-copy-assets.sh    
-          ls -ltra          
           cd ..          
-          ls -ltra
 
           awk '{sub(/@dev/,"@${{ github.event.inputs.python-repo }}")}1' requirements.txt > temp.txt && mv temp.txt requirements.txt 
           
@@ -95,12 +85,19 @@ jobs:
           cd terminus-python
           behave test/features --junit
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
+      - name: Publish Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        if: always()
         with:
-          report_paths: 'terminus-python/reports/*.xml'
-          detailed_summary: true
-          include_passed: true
-          annotate_notice: true
-          summary: true
+          files: |
+            terminus-python/reports/*.xml    
+
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v4
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          report_paths: 'terminus-python/reports/*.xml'
+#          detailed_summary: true
+#          include_passed: true
+#          annotate_notice: true
+#          summary: true
