action changes

diff --git a/.github/workflows/sdk-dot-net.yml b/.github/workflows/sdk-dot-net.yml
--- a/.github/workflows/sdk-dot-net.yml
+++ b/.github/workflows/sdk-dot-net.yml
@@ -3,10 +3,10 @@ name: CSPR Python SDK Standard Tests
 on:
   workflow_call:
     inputs:
-      java-repo:
-        description: 'Java Repo'
-        required: true
+      dot-net-repo:
+        description: 'C# Repo'
         type: string
+        required: false
       node-version:
         description: 'Node build repo'
         required: true
@@ -47,81 +47,28 @@ jobs:
       - name: Checkout SDK source code
         uses: actions/checkout@v2
         with:
-          repository: casper-sdks/casper-java-sdk
+          repository: make-software/casper-net-sdk
           ref: ${{ inputs.java-repo }}
-          path: casper-java-sdk
-          submodules: true
+          path: casper-net-sdk
 
-      # JDK environment to build the SDK jar
-      - name: Setup SDK Java environment
-        uses: actions/setup-java@v2
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v1
         with:
-          java-version: '11'
-          distribution: 'adopt'
+          dotnet-version: 7.0.x
 
-      #      # Build the SDK jar files
-      #      - name: Build SDK JAR
-      #        working-directory: casper-java-sdk
-      #        run: ./gradlew clean build -x test
-      #
-      #      # Upload the built SDK jar as a project artifact
-      #      - name: Upload SDK jar to artifacts
-      #        uses: actions/upload-artifact@v3
-      #        with:
-      #          name: casper-java-sdk-jar
-      #          path: |
-      #            casper-java-sdk/build/libs/*.jar
-      #
-      #      # Checkout the test platform java code
-      #      - name: Checkout test platform code
-      #        uses: actions/checkout@v2
-      #      - name: Set up JDK 11
-      #        uses: actions/setup-java@v2
-      #        with:
-      #          java-version: '11'
-      #          distribution: 'adopt'
-      #
-      #      # Download the SDK jar artifact
-      #      - name: Download casper-java-sdk-jar artifact
-      #        uses: actions/download-artifact@v3
-      #        with:
-      #          name: casper-java-sdk-jar
-      #
-      #      # Gradle needs execute permissions
-      #      - name: Grant execute permission for gradlew
-      #        run: chmod +x gradlew
+      - name: Restore dependencies
+        run: dotnet restore
 
-      #      - name: Debug
-      #        run: |
-      #          ls -ltra
+      - name: Build
+        run: dotnet build --no-restore
 
-      # Gradle needs execute permissions
-      - name: Run project bootstrap
-        run: |
-          cd casper-java-sdk
-          git submodule init
-          git submodule update --init --recursive
-          git submodule update --remote
-      #          chmod +x script/bootstrap
-      #          ./script/bootstrap
-
-      # Move the assets to their required folders
-      # Run the actual cucumber tests
-      - name: Test with cucumber
-        run: |
-          cd casper-java-sdk
-          cd script
-          chmod +x docker-copy-assets 
-          ./docker-copy-assets
-          ls -ltra
-          cd ..
-          ls -ltra
-          chmod +x gradlew
-          ./gradlew clean cucumberCli -DrootLogger.level=OFF
+      - name: Test
+        run: dotnet test --no-build --logger:junit --results-directory reports
 
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v3
-        if: success() || failure() # always run even if the previous step fails
+        # always run even if the previous step fails
+        if: success() || failure()
         with:
           report_paths: 'reports/*.xml'
           detailed_summary: true
